name: Build Android APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update -y
          sudo apt-get install -y -qq build-essential libffi-dev libssl-dev ffmpeg libtool autoconf automake pkg-config libltdl-dev openjdk-17-jdk ccache zip unzip

      - name: Install Python & Build Tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install "cython==0.29.36" "buildozer==1.5.0"

      - name: Build APK with Buildozer
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Jarvis-APK
          path: bin/*.apk
          
